// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigurnaDob.Api.Data;

#nullable disable

namespace SigurnaDob.Api.Migrations
{
    [DbContext(typeof(SigurnaDobDbContext))]
    partial class SigurnaDobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SigurnaDob.Shared.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CoordinatorId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FamilyContactId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("FamilyContactId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareTaskStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareTaskTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaregiverId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareTaskStatusId");

                    b.HasIndex("CareTaskTypeId");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("ResidentId");

                    b.ToTable("CareTasks");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CareTaskStatuses");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CareTaskTypes");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeePositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("HiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("EmployeePositionId");

                    b.HasIndex("EmployeeStatusId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.EmployeePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EmployeePositions");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.EmployeeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EmployeeStatuses");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.FamilyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("FamilyContacts");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AdmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResidentStatusId");

                    b.HasIndex("RoomId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentActivity", b =>
                {
                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("ResidentId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("ResidentActivities");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentMedia");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResidentStatuses");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RoomStatusId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.RoomStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoomStatuses");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HeldAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedVisitAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitRequestStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("FamilyContactId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("VisitRequestStatusId");

                    b.ToTable("VisitRequests");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VisitRequestStatuses");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Activity", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.Employee", "Coordinator")
                        .WithMany("CoordinatedActivities")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivityType");

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUser", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Employee", "Employee")
                        .WithOne("AppUser")
                        .HasForeignKey("SigurnaDob.Shared.Models.AppUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SigurnaDob.Shared.Models.FamilyContact", "FamilyContact")
                        .WithOne("AppUser")
                        .HasForeignKey("SigurnaDob.Shared.Models.AppUser", "FamilyContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("FamilyContact");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUserRole", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTask", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.CareTaskStatus", "CareTaskStatus")
                        .WithMany("CareTasks")
                        .HasForeignKey("CareTaskStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.CareTaskType", "CareTaskType")
                        .WithMany("CareTasks")
                        .HasForeignKey("CareTaskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.Employee", "Caregiver")
                        .WithMany("AssignedCareTasks")
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SigurnaDob.Shared.Models.Employee", "Coordinator")
                        .WithMany("CoordinatedCareTasks")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("CareTasks")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareTaskStatus");

                    b.Navigation("CareTaskType");

                    b.Navigation("Caregiver");

                    b.Navigation("Coordinator");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Employee", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.EmployeePosition", "EmployeePosition")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeePositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.EmployeeStatus", "EmployeeStatus")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeePosition");

                    b.Navigation("EmployeeStatus");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.FamilyContact", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("FamilyContacts")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Resident", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.ResidentStatus", "ResidentStatus")
                        .WithMany("Residents")
                        .HasForeignKey("ResidentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.Room", "Room")
                        .WithMany("Residents")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResidentStatus");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentActivity", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Activity", "Activity")
                        .WithMany("ResidentActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("ResidentActivities")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentMedia", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("Media")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Room", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.RoomStatus", "RoomStatus")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomStatus");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequest", b =>
                {
                    b.HasOne("SigurnaDob.Shared.Models.Employee", "Coordinator")
                        .WithMany("CoordinatedVisitRequests")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SigurnaDob.Shared.Models.FamilyContact", "FamilyContact")
                        .WithMany("VisitRequests")
                        .HasForeignKey("FamilyContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.Resident", "Resident")
                        .WithMany("VisitRequests")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SigurnaDob.Shared.Models.VisitRequestStatus", "VisitRequestStatus")
                        .WithMany("VisitRequests")
                        .HasForeignKey("VisitRequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinator");

                    b.Navigation("FamilyContact");

                    b.Navigation("Resident");

                    b.Navigation("VisitRequestStatus");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Activity", b =>
                {
                    b.Navigation("ResidentActivities");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskStatus", b =>
                {
                    b.Navigation("CareTasks");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.CareTaskType", b =>
                {
                    b.Navigation("CareTasks");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Employee", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("AssignedCareTasks");

                    b.Navigation("CoordinatedActivities");

                    b.Navigation("CoordinatedCareTasks");

                    b.Navigation("CoordinatedVisitRequests");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.EmployeePosition", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.EmployeeStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.FamilyContact", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("VisitRequests");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Resident", b =>
                {
                    b.Navigation("CareTasks");

                    b.Navigation("FamilyContacts");

                    b.Navigation("Media");

                    b.Navigation("ResidentActivities");

                    b.Navigation("VisitRequests");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.ResidentStatus", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.Room", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.RoomStatus", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SigurnaDob.Shared.Models.VisitRequestStatus", b =>
                {
                    b.Navigation("VisitRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
